# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MasterCardHack' do
pod 'SwiftQRCode'
use_frameworks!
end

target 'MasterCardHackTests' do

end

target 'MasterCardHackUITests' do

end

